@base_url = http://localhost:8080

###

# @name create_users
POST {{base_url}}/users
Content-Type: application/json

{
    "name": "Bruno",
    "email": "bruno@email.com"
}

###

# @name create_event
POST {{base_url}}/events
Content-Type: application/json

{
    "title": "Aniversário do meu filho",
    "description": "Obrigado por comparecer ao niver",
    "date": "2025-10-25T17:00",
    "usersId": "cmfvpgqg40000gfqzcyiyqn2m",
    "guests": [
        {"name": "Vanessa", "email": "vanessa@email.com"},
        {"name": "edu", "email": "edu@email.com"}
    ]
}

###

# @name get_events_users
GET {{base_url}}/events-users/cmfvpgqg40000gfqzcyiyqn2m
